parameters:
    verint.feedback.class:   Verint\FeedbackBundle\SoapClient\Feedback

services:
    verint.feedback:
        class: '%verint.feedback.class%'
        arguments:
            - '%verint.efm.config%'
            - '@doctrine.orm.entity_manager'